stages:
  - build
  - test
  - deploy

.staging_variables: &staging_variables
  DISTRIBUTION_ID: $STAGING_DISTRIBUTION_ID
  S3_BUCKET_NAME: $STAGING_S3_BUCKET_NAME
  ENV_FILE: $STAGING_ENV_FILE

.production_variables: &production_variables
  DISTRIBUTION_ID: $PRODUCTION_DISTRIBUTION_ID
  S3_BUCKET_NAME: $PRODUCTION_S3_BUCKET_NAME
  ENV_FILE: $PRODUCTION_ENV_FILE

.build:
  stage: build
  image: node:16-alpine
  script:
    - cp $ENV_FILE .env
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 20 mins

build:staging:
  extends: .deployment
  variables:
    <<: *staging_variables
  environment:
    name: staging
  only:
    - main

build:production:
  extends: .deployment
  variables:
    <<: *production_variables
  environment:
    name: production
  only:
    - production

packages-vulnerability: 
  stage: test
  image: node:16-alpine
  dependencies:
    - build
  script:
    - npm audit --audit-level=critical
  only:
    - main
    - production

.deployment:
  stage: deploy
  image:
     name: amazon/aws-cli:latest
     entrypoint: [""]
  script:
    - echo "Deployment to $S3_BUCKET_NAME"
    - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'

deployment:staging:
  extends: .deployment
  variables:
    <<: *staging_variables
  environment:
    name: staging
  only:
    - main

deployment:production:
  extends: .deployment
  variables:
    <<: *production_variables
  environment:
    name: production
  only:
    - production
