stages:
  - build
  - deploy

build:
  stage: build
  image: node:16-alpine
  script:
      - npm i --force       #TO-DO fix dependencies and change to npm ci
      - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 20 mins
  environment:
    name: staging
  only:
    - main

deployment-staging:
  stage: deploy
  variables:
    S3_BUCKET_NAME: $STAGING_S3_BUCKET_NAME
  image:
     name: amazon/aws-cli:latest
     entrypoint: [""]
  dependencies:
    - build
  script:
    - echo "$S3_BUCKET_NAME"
    - aws s3 sync build/ s3://staging.telcorewards.ca --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
  environment:
    name: staging
  only:
    - main

deployment-production:
  stage: deploy
  variables:
    S3_BUCKET_NAME: $PRODUCTION_S3_BUCKET_NAME
  image:
     name: amazon/aws-cli:latest
     entrypoint: [""]
  dependencies:
    - build
  script:
    - echo "$S3_BUCKET_NAME"
    - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
  environment: production
  only: 
    - production
