image: docker:latest

stages:
  - build
  - deploy

build:
  stage: build
  image: node:16-alpine
  script:
      - npm i --force
      - npm run build
      - ls
  artifacts:
    paths:
      - dist/
    expire_in: 20 mins
  environment:
    name: staging
  only:
    - main

deploy:
  stage: deploy
  image: python:3.5
  dependencies:
    - build
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export S3_BUCKET_NAME=$S3_BUCKET_NAME
    - export DISTRIBUTION_ID=$DISTRIBUTION_ID
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:$PATH
    - aws s3 sync --acl public-read --delete dist $S3_BUCKET_NAME
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
  environment:
    name: staging
  only:
    - main