stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

build:
  stage: build
  image: node:16-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 20 mins
  only:
    - main
    - production

packages-vulnerability: 
  stage: test
  image: node:16-alpine
  script:
    - npm audit --audit-level=critical
  only:
    - main
    - production

deployment-staging:
  stage: deploy
  variables:
    S3_BUCKET_NAME: $STAGING_S3_BUCKET_NAME
    DISTRIBUTION_ID: $STAGING_DISTRIBUTION_ID
  image:
    name: amazon/aws-cli:latest
    entrypoint: ['']
  dependencies:
    - build
  script:
    - echo "Deployment to $S3_BUCKET_NAME"
    - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
  environment:
    name: staging
  only:
    - main

deployment-production:
  stage: deploy
  variables:
    S3_BUCKET_NAME: $PRODUCTION_S3_BUCKET_NAME
    DISTRIBUTION_ID: $PRODUCTION_DISTRIBUTION_ID
  image:
    name: amazon/aws-cli:latest
    entrypoint: ['']
  dependencies:
    - build
  script:
    - echo "Deployment to $S3_BUCKET_NAME"
    - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
  environment: production
  only:
    - production
