const locale = {
  // SIGNUP
  CREATE_ACCOUNT: 'Create an account',
  PHONE: 'Phone Number',
  CONTINUE: 'Continue',
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  LOGIN: 'Log In',
  VERIFY_PHONE_NUMBER: 'Verify phone number',
  ENTER_THE_CODE_WE_HAVE_SEND: 'Enter the code we’ve sent by SMS to',
  HAVE_NOT_RECEIVED_SMS: 'Haven’t received SMS?',
  SEND_AGAIN: 'Send again',
  BACK: 'Back',
  ADD_PERSONAL_DETAILS: 'Add personal details',
  FIRST_NAME: 'First name',
  LAST_NAME: 'Last name',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  ADD_NETWORK_DETAILS: 'Add network details',
  MOBILE_NETWORK_CARRIER: 'Mobile network carrier',
  PHONE_PLAN: 'Phone plan',
  MONTHLY: 'Monthly',
  PREPAID: 'Prepaid',
  SIGN_UP: 'Sign Up',
  // LOGIN
  FORGOT_PASSWORD: 'Forgot password?',
  NEW_TO_TELCOREWARDS: 'New to Telco Rewards?',
  // RESET PASSWORD BY PHONE
  DO_NOT_HAVE_ACCESS_TO_PHONE: 'Do not have access to this phone?',
  USE_EMAIL: 'Use email',
  BACK_TO_LOGIN: 'Back to Log in',
  SEND_CODE: 'Send code',
  SET_NEW_PASSWORD: 'Set new password',
  CONFIRM_NEW_PASSWORD: 'Confirm new password',
  // RESET PASSWORD BY EMAIL
  ENTER_THE_EMAIL_ADDRESS_YOU_REGISTER_WITH:
    'Enter the email address you used to register with.',
  BACK_TO_LOGIN: 'Back to Log in',
  CHECK_YOUR_INBOX: 'Check your inbox',
  LINK_WAS_SENT_TO: 'A link was sent to',
  TO_RESET_YOUR_PASSWORD_CHECK_SPAM_FOLDER:
    'to reset your password. If you don’t see it in your inbox, remember to check your spam folder.',
  // HOME PAGE
  SEARCH_STORES: 'Search stores',
  FEATURES_STORES: 'Featured Stores',
  ALL_STORES: 'All Stores',
  FASHION: 'Fashion',
  ENTERTAINMENT: 'Entertainment',
  ELECTRONICS: 'Electronics',
  FOOD_AND_GROCERY: 'Food & Grocery',
  BABY_KIDS_TOYS: 'Baby, Kids & Toys',
  BOOKS: 'Books',
  HOME_AND_GARDEN: 'Home & Garden',
  BEAUTY_AND_HEALTH: 'Beauty & Health',
  SPORTS_AND_OUTDOOR: 'Sports & Outdoor',
  AUTO: 'Auto',
  PET_SUPPLIES: 'Pet Supplies',
  HARDWARE_AND_TOOLS: 'Hardware & Tools',
  FILTER: 'Filter',
  HOW_TO_USE_TELCOREWARDS: 'HOW TO USE TELCO REWARDS?',
  SELECT_ONLINE_SHOP: 'Select an online shop',
  GO_TO_ONE_OF_2930_STORES: 'Go to one of 2930+ stores',
  COMPLETE_PURCHASE: 'Complete purchase',
  PURCHASE_GOODS_AND_SERVICES: 'Purchase goods and services as usual',
  RECEIVE_CASHBACK: 'Receive cashback',
  GET_PART_OF_THE_MONEY: 'Get part of the money you spent back',
  DOWNLOAD_THE_APP: 'Download the App',
  // SETTINGS
  PERSONAL_INFORMATION: 'Personal information',
  MISSING_TRANSACTION: 'Missing transaction',
  GET_HELP: 'Get help',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  PRIVACY_POLICY: 'Privacy Policy',
  LOGOUT: 'Log out',
  AVAILABLE: 'AVAILABLE',
  // STORE PAGE
  SHOP_NOW: 'Shop Now',
  LOG_IN_TO_SHOP: 'Log in to shop',
  BASE_REWARD: 'Base reward',
  SHOP_NOW: 'Shop Now',
  // CASHBACK
  NO_REWARDS_YET: 'No rewards yet',
  REDUCE_YOUR_MOBILE_BILL: 'Reduce your mobile bill with cash-back.',
  DONT_HAVE_ACCOUNT: 'Don’t have an account?',
  CASHBACK: 'Cash-back',
  WITHDRAWALS: 'Withdrawals',
  PENDING: 'PENDING',
  TOTAL: 'TOTAL',
  WITHDROW: 'Withdrow',
  ADDED_TO_MOBILE_BALANCE: 'ADDED TO MOBILE BALANCE',
  STILL_AVAILABLE: 'STILL AVAILABLE',
  SHOP_FOR_MORE_CASH_BACK: 'Shop for more cash-back',
  // MISSING TRANSACTION
  REPORT_MISSING_TRANSACTION: 'Report a missing transaction',
  STORE: 'Store',
  DATE_OF_PURCHASE: 'Date of purchase',
  PURCHASE_TYPE: 'Purchase type',
  PAYMENT_METHOD: 'Payment method',
  PROOF_OF_PAYMENT:
    'Please upload a receipt or bank statement to show the proof of purchase value, transaction date, payment card details and retailer. We need to see all this information to confirm your transaction with the retailer.For security, please do not include your full card number, expiry date of card or any other account information other than the last 4 digits of the card, transaction date, amount and retailers',
  UPLOAD_PHOTO: 'Upload Photo',
  SUBMIT_FOR_REVIEW: 'Submit for review',
  PURCHASE_TYPE: 'Purchase type',
  MOBILE: 'Mobile',
  DESKTOP: 'Desktop',
  CREDIT_CARD: 'Credit Card',
  DEBIT_CARD: 'Debit Card',
  INSTALLMENT_PAYMENTS: 'Installment payments',
};

export default locale;
